# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 04:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=50)),
                ('product_image', models.ImageField(upload_to='productImage')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('isDelete', models.BooleanField(default=False)),
                ('product_unit', models.CharField(default='500g', max_length=20)),
                ('product_click', models.IntegerField(verbose_name='点击量')),
                ('product_description', models.CharField(max_length=100, verbose_name='简介')),
                ('product_detail', tinymce.models.HTMLField()),
                ('product_remain', models.IntegerField(default=0, verbose_name='库存')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_manage.Category')),
            ],
        ),
    ]
