# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 03:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_brand',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='product_manage.Brand'),
        ),
    ]
