# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 04:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_manage', '0004_auto_20170920_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_category',
        ),
    ]
