# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 04:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_manage', '0006_auto_20170920_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_manage.Category'),
        ),
    ]
