# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_manage', '0007_auto_20170920_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(upload_to='static/productImage'),
        ),
    ]
