# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('user_password', models.CharField(max_length=255)),
                ('user_email', models.EmailField(max_length=30)),
                ('user_address', models.CharField(default='', max_length=100)),
                ('user_phone', models.CharField(default='', max_length=11)),
            ],
        ),
    ]
